-- MySQL Script generated by MySQL Workbench
-- Sat Feb  7 15:27:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `player_id` INT NOT NULL,
  `player_name` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL,
  `Aadhaar` VARCHAR(12) NOT NULL,
  `Phone_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizer` (
  `organizer_id` INT NOT NULL,
  `organizer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`organizer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `match_id` INT NOT NULL,
  `match_name` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  `match_date` DATE NULL,
  `player_limit` INT NULL,
  `bull_limit` INT NULL,
  `registered_player_count` INT NULL,
  `registered_bull_count` INT NULL,
  `organizer_id` INT NOT NULL,
  `status` ENUM("Scheduled", "Live", "Completed") NULL DEFAULT 'Scheduled',
  PRIMARY KEY (`match_id`),
  CONSTRAINT `fk_Match_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_organizer1`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `mydb`.`organizer` (`organizer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Match_location1_idx` ON `mydb`.`Match` (`location_id` ASC) VISIBLE;

CREATE INDEX `fk_Match_organizer1_idx` ON `mydb`.`Match` (`organizer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch` (
  `batch_id` INT NOT NULL,
  `batch_name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`batch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`round_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`round_type` (
  `round_type_id` INT NOT NULL,
  `round_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`round_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player_Match_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player_Match_History` (
  `match_id` INT NOT NULL,
  `round_type_id` INT NOT NULL,
  `batch_id` INT NOT NULL,
  `bull_caught` INT ZEROFILL NULL,
  `penalties` INT ZEROFILL NULL,
  `player_id` INT NOT NULL,
  `status` ENUM("registered", "approved") NULL DEFAULT 'registered',
  PRIMARY KEY (`match_id`, `round_type_id`, `player_id`),
  CONSTRAINT `fk_Player_Match_History_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`Match` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_Match_History_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_Match_History_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `mydb`.`batch` (`batch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_Match_History_round_type1`
    FOREIGN KEY (`round_type_id`)
    REFERENCES `mydb`.`round_type` (`round_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Player_Match_History_Match1_idx` ON `mydb`.`Player_Match_History` (`match_id` ASC) VISIBLE;

CREATE INDEX `fk_Player_Match_History_player1_idx` ON `mydb`.`Player_Match_History` (`player_id` ASC) VISIBLE;

CREATE INDEX `fk_Player_Match_History_batch1_idx` ON `mydb`.`Player_Match_History` (`batch_id` ASC) VISIBLE;

CREATE INDEX `fk_Player_Match_History_round_type1_idx` ON `mydb`.`Player_Match_History` (`round_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `owner_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Aadhaar` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `adhaar_UNIQUE` ON `mydb`.`owner` (`Aadhaar` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`bull_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bull_breed` (
  `bull_breed_id` INT NOT NULL,
  `bull_breed_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bull_breed_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bull_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bull_table` (
  `bull_id` INT NOT NULL,
  `bull_name` VARCHAR(45) NULL,
  `age` INT(2) NULL,
  `owner_id` INT NULL,
  `breed_id` INT NULL,
  `fitness_certificate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bull_id`),
  CONSTRAINT `fk_bull_table_owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_table_bull_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`bull_breed` (`bull_breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bull_table_owner1_idx` ON `mydb`.`bull_table` (`owner_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_table_bull_breed1_idx` ON `mydb`.`bull_table` (`breed_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prize` (
  `prize_id` INT NOT NULL,
  `prize` VARCHAR(45) NULL,
  `prize_provided_by` VARCHAR(45) NULL,
  PRIMARY KEY (`prize_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bull_match_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bull_match_history` (
  `match_id` INT NOT NULL,
  `bull_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `aggression` INT ZEROFILL NOT NULL,
  `play_area` INT ZEROFILL NOT NULL,
  `difficulty` INT ZEROFILL NOT NULL,
  `penalties` INT NULL,
  `release_count` INT NULL,
  `prize_id` INT NOT NULL,
  `round_type_id` INT NOT NULL,
  `winner` TINYINT(0) NULL,
  `status` ENUM("registered", "approved") NULL DEFAULT 'registered',
  PRIMARY KEY (`match_id`, `bull_id`, `round_type_id`),
  CONSTRAINT `fk_bull_match_history_bull_table1`
    FOREIGN KEY (`bull_id`)
    REFERENCES `mydb`.`bull_table` (`bull_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_match_history_prize1`
    FOREIGN KEY (`prize_id`)
    REFERENCES `mydb`.`prize` (`prize_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_match_history_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_match_history_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`Match` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_match_history_round_type1`
    FOREIGN KEY (`round_type_id`)
    REFERENCES `mydb`.`round_type` (`round_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bull_match_history_bull_table1_idx` ON `mydb`.`bull_match_history` (`bull_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_match_history_prize1_idx` ON `mydb`.`bull_match_history` (`prize_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_match_history_player1_idx` ON `mydb`.`bull_match_history` (`player_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_match_history_round_type1_idx` ON `mydb`.`bull_match_history` (`round_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`bull_player_interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bull_player_interaction` (
  `match_id` INT NOT NULL,
  `round_type_id` INT NULL,
  `player_id` INT NOT NULL,
  `bull_id` INT NOT NULL,
  `hold_sequence` INT NULL,
  `hold_duration` INT NULL,
  PRIMARY KEY (`match_id`, `player_id`, `bull_id`),
  CONSTRAINT `fk_bull_player_interaction_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`Match` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_player_interaction_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_player_interaction_bull_table1`
    FOREIGN KEY (`bull_id`)
    REFERENCES `mydb`.`bull_table` (`bull_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bull_player_interaction_round_type1`
    FOREIGN KEY (`round_type_id`)
    REFERENCES `mydb`.`round_type` (`round_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bull_player_interaction_player1_idx` ON `mydb`.`bull_player_interaction` (`player_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_player_interaction_bull_table1_idx` ON `mydb`.`bull_player_interaction` (`bull_id` ASC) VISIBLE;

CREATE INDEX `fk_bull_player_interaction_round_type1_idx` ON `mydb`.`bull_player_interaction` (`round_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `pass_hash` VARCHAR(255) NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `full_name` VARCHAR(45) NOT NULL,
  `role` ENUM("admin", "registrar", "scorer") NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `admin_username_UNIQUE` ON `mydb`.`app_user` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `admin_id_UNIQUE` ON `mydb`.`app_user` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
